In [3]:
import numpy as np
a = np.array([[1., 2.], [3., 4.]])
b = np.array([5., 6., 7., 8.])
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [5]:
arr = np.arange(12).reshape((3, 4))

In [7]:
print(arr)
print("Transpose using .T")
print(arr.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [9]:
arr1=np.transpose(arr,(1,0))
print(arr1)
arr2=np.transpose(arr,(0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
arr1=np.transpose(arr)

In [13]:
print(arr1)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
